destination:    ./_site
lsi:            false
markdown:       rdiscount
pygments:       true
permalink:      /:year/:month/:title
static_root:    "http://static.mikewest.org/20100307"
content_root:   /home/mikewest/Repositories/mgc/
tag_root:       /tags
