destination:    ./_site
lsi:            false
markdown:       rdiscount
pygments:       true
permalink:      /:year/:month/:title
static_root:    /static
content_root:   /home/mikewest/Repositories/mgc/
tag_root:       /tags
